[Messenger]
apkmirror-dlurl = "https://apkmirror.com/apk/facebook-2/messenger/"
excluded-patches = "'Hide inbox subtabs'"

[Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
excluded-patches = "'Custom branding'"

[Twitch]
apkmirror-dlurl = "https://apkmirror.com/apk/twitch-interactive-inc/twitch/"

[Twitter]
apkmirror-dlurl = "https://apkmirror.com/apk/twitter-inc/twitter/"
excluded-patches = "'Hide recommended users'"

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
excluded-patches = "'Shorts autoplay' 'Open Shorts in regular player'"
patcher-args = "-e 'Hide Shorts components' -OhideShortsAppShortcut=True"

[Google Photos]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/"
included-patches = "'Enable DCIM folders backup control'"

[MyFitnessPal]
apkmirror-dlurl = "https://www.apkmirror.com/apk/myfitnesspal-inc/calorie-counter-myfitnesspal/myfitnesspal-calorie-counter-25-50-0-release/"

[Pixiv]
apkmirror-dlurl = "https://www.apkmirror.com/apk/pixiv-inc/"

[Viber]
apkmirror-dlurl = "https://www.apkmirror.com/apk/viber-media-s-a-r-l/"
included-patches = "'Hide Ads'"
exclusive-patches = true
