[Messenger]
apkmirror-dlurl = "https://apkmirror.com/apk/facebook-2/messenger/"
excluded-patches = "'Hide inbox subtabs'"

[Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
excluded-patches = "'Custom branding'"

[Twitch]
apkmirror-dlurl = "https://apkmirror.com/apk/twitch-interactive-inc/twitch/"

[Twitter]
apkmirror-dlurl = "https://apkmirror.com/apk/twitter-inc/twitter/"
excluded-patches = "'Hide recommended users'"

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
excluded-patches = "'Shorts autoplay' 'Open Shorts in regular player'"
patcher-args = "-e 'Hide Shorts components' -OhideShortsAppShortcut=True"

